### ISSUE TITLE
Awards requests -> Not working

### ISSUE THREAD

**Issue by deidyomega** [deidyomega/ataa_horse_db#3]
Users should be able to request new awards.  Form is up, but not linked.

**Comment by birdypup** [comment]
Need a streamlined, in-site form that allows supporting documents (scans,files) to be submitted along with request to change registration information or to add accomplishments. This verifies authenticity with ATAA/VNIIK or the show host.

3 Sections:
- Have text-box request entry field for user to describe change wanted, and underneath have file uploader (able to handle at least 3 files) to be submitted with the text entry request.
- Have photo uploader (Same as above) section for adding photos for review
-Have input boxes (3-5) for accomplishment submissions for review, and underneath have the file uploader for supporting documents (same number as entry fields)

**Comment by birdypup** [comment]
What if this existed as a separate page that the request button links to and then on that page the user selects which action they want. "Add an Accomplishment", "Change Horse Registration Information", and "Submit Photo to Horse's Gallery". Top of this page could say "Which type of request would you like to make for :insert horse's name that the request is for:? All requests will be submitted for review by the registry admin." At bottom of the page, add a Need Help link/button that goes to Contact.

**Comment by deidyomega** [comment]
1) UI is complete
2) Need to get server posting results to email
