### ISSUE TITLE
Members need to be able to request horses they own to be added to their owned horses in Dash

### ISSUE THREAD

**Issue by birdypup** [deidyomega/ataa_horse_db#31]
When members (logged in) visit a horse page, there should be a request/claim ownership sort of tool under the Breeder/Owner section. This should allow the member to submit a request from that page to be added as the owner or breeder, depending on which was selected or both. Perhaps in the request it just offers two checkboxes: "Declare Ownership of Horse" and "Declare Yourself as the Breeder of this Horse" with a supporting document as before (for bill of sale, breeder pages, etc).

**Comment by deidyomega** [comment]
1.5 hours
