### ISSUE TITLE
Declare Owner/Breeder Text Change

### ISSUE THREAD

**Issue by birdypup** [deidyomega/ataa_horse_db#32]
Change the top text to... "Please attach your supporting documents below and provide here any further information regarding your status as breeder and/or owner. Note: Ownership cannot be changed in the registry until the horse is officially registered under the new owner, which can be done by filling out a Transfer of Ownership on the ATAA site."

Bottom text change to... "Upload 1-2 supporting documents here for review of your declaration as breeder and/or owner. These must show your name and the horse's name, and may include: a bill of sale, farm breeding record, ownership of dam and sire, stallion service certificate, transfer of ownership, registration papers, and/or both ATAA and VNIIK papers. Please chose the most appropriate documents for your claim. Note: If no owner/breeder is currently listed for this horse, you only need to provide the ATAA and VNIIK registration papers for purebreds and, for partbreds, just the ATAA registration certificate."

**Comment by deidyomega** [comment]
+ Formating Cleanup

45 min
